In [21]:
import numpy as np
import os.path as op
import matplotlib.pyplot as plt
from floater import generators
%matplotlib inline

In [37]:
outdir = '/swot/SUM01/takaya/ftle/input/'
res = 1
tp = '>f8'
nx = 2000
ny = 2000

In [38]:
bathy = -1.*np.ones((ny,nx))
bathy[0,:] = 0.
bathy[-1,:] = 0.
# bathy[:,0] = 0.
# bathy[:,-1] = 0.
print(bathy)
bathy.astype(tp).tofile(outdir + 'BATHY_floater_%03dkm_x%04d-y%04d.bin' % (res,nx,ny))

[[ 0.  0.  0. ...  0.  0.  0.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 ...
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [ 0.  0.  0. ...  0.  0.  0.]]


In [39]:
delta = 200.
fs = generators.FloatSet(xlim=(.005e5,19.995e5), ylim=(.005e5,19.995e5), dx=delta, dy=delta)

fs.to_mitgcm_format(op.join(outdir,'flt_initpo_%03dm_2d_x%04d-y%04d.bin' % (int(delta),nx,ny)), 
                    iup=0, mesh='rect', read_binary_prec=64)
fs.to_pickle(op.join(outdir,'floatset_%03dm_2d_x%04d-y%04d.pkl' % (int(delta),nx,ny)))

In [40]:
da = np.fromfile(op.join(outdir,'flt_initpo_%03dm_2d_x%04d-y%04d.bin' % (int(delta),nx,ny)), dtype='>f8')
N0 = da.shape[0]
da = da.reshape((int(N0/9),9))
da.shape

(99900026, 9)

In [17]:
da[:,2]

array([0.000000e+00, 5.625000e+02, 6.875000e+02, ..., 5.991875e+05,
       5.993125e+05, 5.994375e+05])

In [18]:
da[:,3]

array([     0. ,    562.5,    562.5, ..., 399437.5, 399437.5, 399437.5])

In [19]:
da[:,6]

array([0., 0., 0., ..., 0., 0., 0.])

In [36]:
19.995e5

1999500.0